management.endpoints.web.exposure.include: "*"

ribbon:
  serverListRefreshInterval: 1000
  ConnectTimeout: 600000
  ReadTimeout: 300000

hystrix.command.default.execution.isolation:
    thread.timeoutInMilliseconds: 10000
    strategy: THREAD

feign.hystrix.enabled: true

hazelcast.max.no.heartbeat.seconds: 6

tsp-application.name: tsp
distance-application.name: distance
